language: python
python:
  - "3.7"
install: "pip install -r requirements.txt"
# command to run tests
script: bash ./test.sh
env:
  global:
  - TESTMODULE: picture.py
  - GH_REPO: github.com/Runpython-IntroProgramming/tests.git
